apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ng-deploy
  name: ng-deploy
spec:
  ports:
  - name: 3080-80
    port: 3080
    protocol: TCP
    targetPort: 80
  selector:
    app: ng-deploy
  type: NodePort
status:
  loadBalancer: {}
