apiVersion: v1
kind: ConfigMap
metadata:
  # namespace: dev
  name: redis-config
  labels:
    app: redis
data:
  redis.conf: |-
    dir /srv
    port 6379
    #bind 0.0.0.0
    #bind * -::* 
    appendonly yes
    protected-mode no
    daemonize no
    requirepass 123456
    pidfile /srv/redis-6379.pid