apiVersion: v1
kind: Service
metadata:
  # namespace: dev
  creationTimestamp: null
  labels:
    app: redis
  name: redis-svc
spec:
  ports:
  - name: tcp
    port: 30379
    protocol: TCP
    targetPort: 6379
    nodePort: 31379
  selector:
    app: redis
  type: NodePort
status:
  loadBalancer: {}